- hosts: localhost
  # any_errors_fatal: True
  gather_facts: False
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: challenge
    image_tag: 0.0.2
    replicas: 3

  roles:
    - role: deploy-server

